#!/bin/sh


alpha='dd'
background='00000000'
selection='#44475a'
comment='#6272a4'
yellow='#f1fa8c'
orange='#ffb86c'
red='#ff5555'
blue='#0099cc'
cyan='#8be9fd'
green='#50fa7b'
magenta='#ff79c6'

i3lock \
--insidever-color=$selection$alpha \
--insidewrong-color=$selection$alpha \
--inside-color=$selection$alpha \
--ringver-color=$blue$alpha \
--ringwrong-color=$red$alpha \
--ring-color=$blue$alpha \
--line-uses-ring \
--keyhl-color=$green$alpha \
--bshl-color=$orange$alpha \
--separator-color=$selection$alpha \
--verif-color=$green \
--wrong-color=$red \
--modif-color=$red \
--layout-color=$blue \
--date-color=$blue \
--time-color=$blue \
--screen 1 \
--clock \
--indicator \
--time-str="%H:%M:%S" \
--date-str="%A %e %B %Y" \
--verif-text="Checking..." \
--wrong-text="Wrong pswd" \
--noinput-text="No Input" \
--lock-text="Locking..." \
--lockfailed-text="Lock Failed" \
--radius=120 \
--ring-width=8 \
--pass-media-keys \
--pass-screen-keys \
--pass-volume-keys
